### ISSUE TITLE
Harmonize/ontologize the CHOP P30 Histolgoy file cg_bh_path_match.xlsx

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/Histologies#1]
https://github.com/PediatricOpenTargets/Histologies/blob/main/CHOP_P30/cg_bh_path_match.xlsx needs to have its terms harmonized to the actual EFO/histology ID based on path diagnosis (and how well it matches or does not match our existing v10 histologies: see Reference folder).

DGD histology Mapping (Run, Deanne, Sangeeta)

1. v10 primary histology file is in the release baseline v10 
2. Github file is the mapping of histologies to EFO/MONDO IDs: [https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/efo-mondo-mapping/results/efo-mondo-map.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/efo-mondo-mapping/results/efo-mondo-map.tsv)  (need to add column: NCIT)
3. DGD histology annotation file **cg_bhc_path_match.xls**:
    a.  Activity file at [https://github.com/PediatricOpenTargets/Histologies/tree/main/CHOP_P30](https://github.com/PediatricOpenTargets/Histologies/tree/main/CHOP_P30)
    b. First tab: **has exact match:** repesents pairs of diagnosis/primary site that are matched by the v10 primary histology file (in Box)
    c. Second tab: **match by path diagnosis**: Only matched by pathology diagnosis in the DGD cohort.
    d. **need_manual_curation** tab:  This path diagnosis does not have a way to map to cancer group. Everything in this tab in green is "we have exact match— typo or standardized" Darker green - removed information on remission etc to make it more conventional. Grey is typos, dashes, etc.  Yellow is not sure what to do with those.  Light orange is going up the OLS tree (less specific), darker orange is "not sure" on ontology.
    e. Last sheet is the key to the analysis.

**Comment by jharenza** [comment]
This was completed with v11.
